# Generated by Django 4.2.9 on 2026-03-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_investor_outboxevent_startup_remove_review_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
