# Generated by Django 4.2.9 on 2026-03-21 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_startup_company_name_alter_startup_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='interests',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='AvailabilityTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_templates', to='api.investor')),
            ],
            options={
                'db_table': 'availability_templates',
            },
        ),
    ]
