# Generated by Django 5.0.3 on 2026-03-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchmakingOutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'matchmaking_outbox_events',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StartupSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_id', models.BigIntegerField()),
                ('similar_startup_id', models.BigIntegerField()),
                ('similarity_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'startup_similarities',
                'ordering': ['-similarity_score'],
                'unique_together': {('startup_id', 'similar_startup_id')},
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('startup_id', models.BigIntegerField()),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('click', 'Click'), ('pitch_request', 'Pitch Request'), ('like', 'Like'), ('review', 'Review')], max_length=20)),
                ('weight', models.FloatField(default=1.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_interactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'startup_id'], name='user_intera_user_id_5e469e_idx'), models.Index(fields=['user_id', 'created_at'], name='user_intera_user_id_4c8dbb_idx')],
            },
        ),
    ]
