# Generated by Django 5.0.3 on 2026-03-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('similar_product_id', models.IntegerField()),
                ('similarity_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'product_similarities',
                'ordering': ['-similarity_score'],
                'unique_together': {('product_id', 'similar_product_id')},
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('click', 'Click'), ('add_to_cart', 'Add to Cart'), ('purchase', 'Purchase'), ('like', 'Like'), ('review', 'Review')], max_length=20)),
                ('weight', models.FloatField(default=1.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_interactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'product_id'], name='user_intera_user_id_7a46aa_idx'), models.Index(fields=['user_id', 'created_at'], name='user_intera_user_id_4c8dbb_idx')],
            },
        ),
    ]
