# Generated by Django 5.0.3 on 2026-03-23 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingOutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'booking_outbox_events',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PitchBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch_slot_id', models.BigIntegerField()),
                ('status', models.CharField(choices=[('INITIALIZED', 'Initialized'), ('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='INITIALIZED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pitch_bookings',
            },
        ),
        migrations.CreateModel(
            name='PitchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('pitch_deck_url', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed')], default='REGISTERED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pitch_requests',
            },
        ),
        migrations.CreateModel(
            name='PitchBookingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('RESCHEDULE', 'Reschedule'), ('CANCEL', 'Cancel')], max_length=50)),
                ('old_slot_id', models.BigIntegerField(null=True)),
                ('new_slot_id', models.BigIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_app.pitchbooking')),
            ],
            options={
                'db_table': 'pitch_booking_history',
            },
        ),
        migrations.AddField(
            model_name='pitchbooking',
            name='pitch_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_app.pitchrequest'),
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch_slot_id', models.BigIntegerField()),
                ('investor_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pitch_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_app.pitchrequest')),
            ],
            options={
                'db_table': 'waitlists',
            },
        ),
    ]
