# Generated by Django 4.2.9 on 2026-03-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'processed_messages',
            },
        ),
        migrations.AddField(
            model_name='startup',
            name='funding_goal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='startup',
            name='funding_stage',
            field=models.CharField(choices=[('PRE_SEED', 'Pre-Seed'), ('SEED', 'Seed'), ('SERIES_A', 'Series A'), ('SERIES_B', 'Series B'), ('LATE_STAGE', 'Late Stage')], default='SEED', max_length=20),
        ),
        migrations.AddField(
            model_name='startup',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='team_size',
            field=models.IntegerField(default=1),
        ),
    ]
